### ISSUE TITLE
Param spider always shows 

### ISSUE THREAD

**Issue by shishirs4** [0xKayala/ParamSpider#3]
OOPS!! Timeout Error. Retrying in 2 seconds.
OOPS!! Timeout Error. Retrying in 2 seconds.
OOPS!! Timeout Error. Retrying in 2 seconds.
OOPS!! Timeout Error. Retrying in 2 seconds.

**Comment by tajuislam** [comment]
plz solve this error 

paramspider -h   
Traceback (most recent call last):
  File "/usr/bin/paramspider", line 33, in <module>
    sys.exit(load_entry_point('paramspider==0.1.0', 'console_scripts', 'paramspider')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/paramspider", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by 0xKayala** [comment]
Can you please try it now and let me know if you are still facing the same issue
